CREATE TABLE "GCG_6232_PNL_SCANS"(
 "JOB" CHAR(7) NOT NULL,
 "SUFFIX" CHAR(3) NOT NULL,
 "SEQUENCE" CHAR(6) NOT NULL,
 "PNL_ID" CHAR(30) NOT NULL,
 "FINISH" CHAR(50),
 "STATUS" CHAR(5) NOT NULL,
 "PNL_ACTION" CHAR(25),
 "SCAN_ID" CHAR(3),
 "QTY" NUMERIC(8,3),
 "DATE_SCANNED" DATE,
 "TIME_SCANNED" CHAR(8) );

CREATE INDEX "JOBSUFF0" USING 0  ON "GCG_6232_PNL_SCANS" ( "JOB", "SUFFIX" );
