CREATE TABLE "GCG_6232_PANEL_CRATE" (
 "CRATE_NO" NUMERIC(8,0),
 "JOB" CHAR(7),
 "SUFFIX" CHAR(3),
 "PNL_ID" CHAR(30),
 "FINISH" CHAR(50),
 "SHIPMENT_ID" NUMERIC(8,0),
 "SHIPPED_FLAG" CHAR(1),
 "QTY" NUMERIC(8,3),
 "SHIPPED_DATE" DATE,
 "SEQUENCE" CHAR(6) );

CREATE INDEX "JOBSUFF0" USING 0  ON "GCG_6232_PANEL_CRATE" ( "CRATE_NO", "JOB", "SUFFIX" );
