CREATE TABLE "GCG_6232_IMPORT_INFO" (
 "COMPANY" CHAR(50),
 "IMPORT_NAME" CHAR(50),
 "PROJECT" CHAR(50),
 "JOB" CHAR(50),
 "RELEASE_INFO" CHAR(50),
 "RELEASED_BY" CHAR(50),
 "IMPORT_DATE" CHAR(50) NOT NULL,
 "TOTAL_PANELS" CHAR(50),
 "SUFFIX" CHAR(3) );